{{- if .Values.controller.enabled }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "admissionname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "namespaces", "services"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "admissionname" . }}-role-binding
subjects:
  - kind: ServiceAccount
    name: "{{ template "admissionname" . }}"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "admissionname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}