apiVersion: v1
kind: ConfigMap
metadata:
  name: node-local-dns
  namespace: {{ .Release.Namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  Corefile: |
    .:53 {
        errors
        cache {
          success 9984 30
          denial 9984 5
        }
{{ if .Values.env.enable_log }}
        log
{{ end }}
        reload
        loop
        bind 169.254.20.10
        forward . {{ .Values.env.upstream_ip }} {
          force_tcp
        }
        prometheus :9253
        health 169.254.20.10:8081
    }